"""Adding Due Date to Task

Revision ID: 5f3b416439c0
Revises: 86ed8b6b51ef
Create Date: 2023-11-21 14:30:33.456255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3b416439c0'
down_revision = '86ed8b6b51ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
